name: PR Tests

on:
  pull_request:

jobs:
  test:
    name: mocha test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DATABASE: pgmq
          options: >-
            --health-cmd pg_isready
            --health-interval 2s
            --health-timeout 2s
            --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: install dependencies
        run: pnpm install
      - name: run lint
        run: pnpm run lint
      - name: run prettier
        run: pnpm run format:check
      - name: run tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/pgmq
        run: pnpm run test
